### ISSUE TITLE
CMake to conan

### ISSUE THREAD

**Issue by michkrom** [lammertb/libhttp#68]
Hi,

Any desire to convert libhttp to a CMake-based build system (hence better portability) and perhaps later to a conan package (hence better integration)?

Or perhaps there is a conan recipe somewhere I missed?

Thanks,
Michal

**Comment by lammertb** [comment]
Not yet. In one of my other projects here on GitHub, a volunteer recently offered to convert the project to CMake which caused library incompatibilities on a number of systems. I had to reverse to a previous version to undo the damage.

I have been writing C programs since the VAX-11/750 and have seen many build systems and IDEs come and go. Make is the only tool that survived all those decades and I expect it to be alive another handful of decades. The only thing you need is one executable that is standard in many development environments or can be downloaded for free as GNU Make. Nothing beats Make when it comes to portability.

**Comment by lammertb** [comment]
No cmake in the near future.
