### ISSUE TITLE
Compiling on Linux breaks due to expected usage of strerror_r return value

### ISSUE THREAD

**Issue by Beliriel** [lammertb/libhttp#69]
Compilation on Linux Ubuntu 20.04 stops with following error:

```
src/httplib_error_string.c: In function ‘httplib_error_string’:
src/httplib_error_string.c:170:2: error: ignoring return value of ‘strerror_r’, declared with
attribute warn_unused_result [-Werror=unused-result]
  170 |  strerror_r( error_code, buf, buf_len );
      |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make: *** [Makefile:149: obj/httplib_error_string.o] Error 1
```

I fixed it intermittently by breaking the error message off by returning NULL if `strerror_r` encounters an error itself since it doesn't make sense returning anything if there's no clean error message available:

```
if(strerror_r( error_code, buf, buf_len )) return NULL;
return buf;
```

I guess `strerror_r` instead of simply `strerror` was used to make it thread safe I assume?

Edit: Nice ;)

**Comment by lammertb** [comment]
Thanks for the info. strerror_r was indeed used because of thread safety.
I will try to reproduce the issue here locally. Thanks also for the pull request. I it fixes the issue, I will merge it in the main tree.

**Comment by lammertb** [comment]
I have created a test environment with Ubuntu 20.04 and can reproduce the bug. Expect a fix shortly.

**Comment by lammertb** [comment]
I fixed the issue in https://github.com/lammertb/libhttp/commit/8ed6823cdee0d3b75b4adecb8bdd4a6c2921a702

I didn't use your pull request, because the problem was bigger than just checking the return value. Two versions of strerror_r exist, one Posix compliant and the other GNU compliant. They both have different return types (int vs. char *) and the GNU version may in some cases not store the error message in the user provided buffer, but return a pointer to a static string instead.

The fix addresses both this GNU return value issue and your compiler warning on Ubuntu 20.04.
